Comment out MonoVM icalls
These icalls make CoreCLR JIT crash when the runtime is statically
linked. JIT eagerly tries to compile them, even tough the code path
is not taken, and that causes it to abort the app because CoreCLR
disallows icalls/ecalls in non-system modules.

Removing the icalls moves past that problem, but then we hit this
error: https://github.com/dotnet/runtime/blob/7889937aae942f9ad369ca9e186104c21d87a187/src/coreclr/vm/jithelpers.cpp#L1853